remote_theme: pages-themes/minimal@v0.2.0


title: Nidodkin_media
description: Сайт про мою оффлайн/онлайн деятельность

# Ссылки на соцсети
social_links:
  telegramm: https://nikodkin-git.github.io/Nikodkin_media/
